version: '3.8'

services:
  postgres:
    image: postgis/postgis:15-3.3
    container_name: rtm-postgres
    environment:
      POSTGRES_USER: nissim
      POSTGRES_PASSWORD: 
      POSTGRES_DB: travel_manager_dev
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init-db.sql:/docker-entrypoint-initdb.d/init-db.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U nissim -d travel_manager_dev"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  postgres_data: