AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: RegularTravelManager API - Lambda Functions

Globals:
  Function:
    Timeout: 30
    Runtime: nodejs18.x
    Environment:
      Variables:
        NODE_ENV: production
        COGNITO_USER_POOL_ID: eu-central-1_TbjGs9xsM
        COGNITO_CLIENT_ID: 56eg6e1l1619nkp69m2i3dek7o

Parameters:
  Environment:
    Type: String
    Default: dev
    AllowedValues: [dev, staging, prod]
    Description: Environment name

Resources:
  # API Gateway
  RTMApi:
    Type: AWS::Serverless::Api
    Properties:
      Name: !Sub rtm-api-${Environment}
      StageName: !Ref Environment
      Cors:
        AllowMethods: "'GET,POST,PUT,DELETE,OPTIONS'"
        AllowHeaders: "'Content-Type,X-Amz-Date,Authorization,X-Api-Key,X-Amz-Security-Token'"
        AllowOrigin: "'*'"
      Auth:
        DefaultAuthorizer: CognitoAuthorizer
        Authorizers:
          CognitoAuthorizer:
            UserPoolArn: !Sub arn:aws:cognito-idp:${AWS::Region}:${AWS::AccountId}:userpool/eu-central-1_TbjGs9xsM

  # Main API Function
  RTMApiFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub rtm-api-${Environment}
      CodeUri: dist/
      Handler: index.handler
      Events:
        ApiEvent:
          Type: Api
          Properties:
            RestApiId: !Ref RTMApi
            Path: /{proxy+}
            Method: ANY
        RootApiEvent:
          Type: Api
          Properties:
            RestApiId: !Ref RTMApi
            Path: /
            Method: ANY
      Policies:
        - AWSLambdaBasicExecutionRole
        - Version: '2012-10-17'
          Statement:
            - Effect: Allow
              Action:
                - cognito-idp:*
                - dynamodb:*
                - location:*
              Resource: '*'

  # DynamoDB Tables
  ProjectsTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: !Sub rtm-projects-${Environment}
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: id
          AttributeType: S
      KeySchema:
        - AttributeName: id
          KeyType: HASH

  SubprojectsTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: !Sub rtm-subprojects-${Environment}
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: id
          AttributeType: S
        - AttributeName: projectId
          AttributeType: S
      KeySchema:
        - AttributeName: id
          KeyType: HASH
      GlobalSecondaryIndexes:
        - IndexName: ProjectIndex
          KeySchema:
            - AttributeName: projectId
              KeyType: HASH
          Projection:
            ProjectionType: ALL

Outputs:
  ApiUrl:
    Description: API Gateway endpoint URL
    Value: !Sub https://${RTMApi}.execute-api.${AWS::Region}.amazonaws.com/${Environment}/
    Export:
      Name: !Sub ${AWS::StackName}-ApiUrl
  
  FunctionName:
    Description: Lambda function name
    Value: !Ref RTMApiFunction
    Export:
      Name: !Sub ${AWS::StackName}-FunctionName